import type { Metadata } from "next";
import "./globals.css";
import UserProvider from "./componentes/UserProvider";
import Footer from "./componentes/footer";
import BotaoBaixeApp from "./componentes/botaoBaixeApp";
import Script from "next/script";
import WatsonChat from "./componentes/watsonChat";

export const metadata: Metadata = {
  title: "CCR",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body>  
        <Script src="https://cdn.userway.org/widget.js" data-account="wWYZXkVTsK"></Script>
        <UserProvider>
          {children}
        </UserProvider>
        <WatsonChat />
        <Footer/>
        <BotaoBaixeApp/>
      </body>
    </html>
  );
}
